services:
  postgres:
    image: postgres:15.1
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  maildev:
    image: maildev/maildev
    expose:
      - 1080
      - 1025

  redis:
    image: redis:7-alpine
    expose:
      - 6379

  api:
    build:
      context: .
      dockerfile: e2e.Dockerfile
